# Generated by Django 5.2 on 2025-10-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dondatphong_paypal_order_id_alter_lichlamviec_ca_lam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangKyNhanTin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Địa chỉ email')),
                ('ngay_dang_ky', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
            ],
            options={
                'verbose_name': 'Đăng ký nhận tin',
                'verbose_name_plural': 'Danh sách đăng ký nhận tin',
            },
        ),
    ]
