# Generated by Django 5.2 on 2025-11-22 06:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dangkynhantin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaGiamGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_code', models.CharField(max_length=20, unique=True)),
                ('phan_tram_giam', models.PositiveIntegerField(default=0, help_text='Nhập số % giảm (VD: 10 là 10%)', validators=[django.core.validators.MaxValueValidator(100)])),
                ('so_tien_giam', models.FloatField(default=0, help_text='Giảm số tiền cố định (VNĐ)')),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField()),
                ('so_luong', models.PositiveIntegerField(default=100)),
                ('trang_thai', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='dondatphong',
            name='tong_tien_thuc_te',
            field=models.FloatField(default=0, help_text='Số tiền sau khi giảm giá'),
        ),
        migrations.AddField(
            model_name='dondatphong',
            name='ma_giam_gia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.magiamgia'),
        ),
    ]
