# Generated by Django 5.2 on 2025-11-29 12:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_magiamgia_dondatphong_tong_tien_thuc_te_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('ma_dg', models.AutoField(primary_key=True, serialize=False)),
                ('diem_so', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('binh_luan', models.TextField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('hien_thi', models.BooleanField(default=True)),
                ('don_dat_phong', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.dondatphong')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.khachhang')),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phong')),
            ],
        ),
    ]
