# Generated by Django 5.2 on 2025-09-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='loai_tk',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('nhan_vien', 'Nhân viên'), ('khach_hang', 'Khách hàng')], default='khach_hang', max_length=20),
        ),
    ]
