# Generated by Django 5.2 on 2025-09-18 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dondatphong',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lichlamviec',
            name='ca_lam',
            field=models.CharField(choices=[('sang', 'Ca sáng (6h30-11h)'), ('chieu', 'Ca chiều (11h-17h)'), ('toi', 'Ca tối (17h-22h)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='tai_khoan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
